import PptxGenJS from "pptxgenjs";

export const generatePPT = async (data) => {
  const ppt = new PptxGenJS();

  ppt.author = "HomeWorkAI";
  ppt.company = "HomeWorkAI";
  ppt.title = data.title;

  // 16:9 widescreen layout (modern default)
  ppt.layout = "LAYOUT_16x9";

  const COLORS = {
    bg: "0F172A", // dark navy background
    accent: "38BDF8", // sky blue accent
    title: "FFFFFF",
    subtitle: "94A3B8",
    heading: "F1F5F9",
    text: "CBD5E1",
    bullet: "38BDF8",
    footer: "64748B",
  };

  const FONT = "Poppins"; // falls back gracefully if not installed on render machine

  // ---------- Title Slide ----------
  const titleSlide = ppt.addSlide();
  titleSlide.background = { color: COLORS.bg };

  // Accent bar
  titleSlide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 3.3,
    w: 1.2,
    h: 0.08,
    fill: { color: COLORS.accent },
  });

  titleSlide.addText(data.title, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1,
    fontSize: 36,
    bold: true,
    color: COLORS.title,
    fontFace: FONT,
    align: "left",
  });

  if (data.subtitle) {
    titleSlide.addText(data.subtitle, {
      x: 0.5,
      y: 3.5,
      w: 9,
      h: 0.8,
      fontSize: 16,
      color: COLORS.subtitle,
      fontFace: FONT,
      align: "left",
    });
  }

  // ---------- Content Slides ----------
  (data.slides || []).forEach((slide, index) => {
    const s = ppt.addSlide();
    s.background = { color: COLORS.bg };

    // Slide number badge
    s.addText(String(index + 1).padStart(2, "0"), {
      x: 0.5,
      y: 0.4,
      w: 1,
      h: 0.5,
      fontSize: 14,
      color: COLORS.accent,
      bold: true,
      fontFace: FONT,
    });

    // Slide title
    s.addText(slide.title, {
      x: 0.5,
      y: 0.9,
      w: 9,
      h: 0.8,
      fontSize: 26,
      bold: true,
      color: COLORS.heading,
      fontFace: FONT,
      align: "left",
    });

    // Divider line under title
    s.addShape(ppt.ShapeType.rect, {
      x: 0.5,
      y: 1.65,
      w: 2,
      h: 0.03,
      fill: { color: COLORS.accent },
    });

    // Bullet points
    const bulletTextRuns = (slide.points || []).map((point) => ({
      text: point,
      options: {
        bullet: { code: "2022", color: COLORS.bullet },
        color: COLORS.text,
        fontSize: 16,
        fontFace: FONT,
        breakLine: true,
        paraSpaceAfter: 14,
      },
    }));

    s.addText(bulletTextRuns, {
      x: 0.6,
      y: 2.1,
      w: 8.8,
      h: 4.5,
      valign: "top",
    });

    // Footer
    s.addText(`${data.title}`, {
      x: 0.5,
      y: 5.3,
      w: 5,
      h: 0.3,
      fontSize: 9,
      color: COLORS.footer,
      fontFace: FONT,
    });

    s.addText(`${index + 1} / ${data.slides.length}`, {
      x: 8.7,
      y: 5.3,
      w: 1,
      h: 0.3,
      fontSize: 9,
      color: COLORS.footer,
      fontFace: FONT,
      align: "right",
    });
  });
  // ---------- Thank You Slide ----------
  const thankYouSlide = ppt.addSlide();
  thankYouSlide.background = { color: COLORS.bg };



  thankYouSlide.addText("Thank You", {
    x: 0.5,
    y: 2.1,
    w: 9,
    h: 1,
    fontSize: 40,
    bold: true,
    color: COLORS.title,
    fontFace: FONT,
    align: "center",
  });

  thankYouSlide.addText(data.title, {
    x: 0.5,
    y: 3.2,
    w: 9,
    h: 0.6,
    fontSize: 14,
    color: COLORS.subtitle,
    fontFace: FONT,
    align: "center",
  });

  thankYouSlide.addText("Generated by HomeWorkAI", {
    x: 0.5,
    y: 5.3,
    w: 5,
    h: 0.3,
    fontSize: 9,
    color: COLORS.footer,
    fontFace: FONT,
  });

  // ---------- Return as Buffer (for S3 upload etc.) ----------
  const buffer = await ppt.write({ outputType: "nodebuffer" });
  return buffer;
};
